function [ b ] = digital_source( par_no, switch_graph )
%DIGITAL_SOURCE Summary of this function goes here
%   Detailed explanation goes here

b = zeros(par_no,1);
for i = 1:par_no
    b(i) = round(rand(1,1)); % Generating a random number and placing it in ith place in b
end

if switch_graph == 1
    figure(1);
    plot(b);
    xlabel('time');
    ylabel('Binary Value');
    title('Graph of the Binary Values generated by the Digital Source');
end

end

